font_settings:
  xtick_size: 12
  ytick_size: 12
  axes_label_size: 16
  legend_size: 12
  title_size: 16
  font_family: serif
text_position:
  title_height: 40
figure_size:
  xdimension: 6
  ydimension: 4
axes_options:
  x_axes_minticks: 4
  x_axes_maxticks: 8
  y_axes_decimalpt: 1
  major_x_tick_length: 5
  major_y_tick_length: 5
  hide_top_spine: true
  hide_right_spine: true
  hide_bottom_spine: false
  hide_left_spine: false
  legend_position: lower right
  legend_columns: 1
  show_legend_frame: true
axes_label_options:
  rotate_x_labels: true
  rotate_at_num_labels: 7
  rotation_angle: 45
plot_data:
  curtailment_property: Curtailment
  plot_title_as_region: true
  include_barplot_load_lines: true
  include_stackplot_load_lines: true
  include_barplot_load_storage_charging_line: true
  include_timeseries_load_storage_charging_line: true
  include_barplot_net_imports: true
  include_stackplot_net_imports: true
load_legend_names:
  load: 'Demand +

    Storage Charging'
  demand: Demand
formatter_settings:
  VoLL: 10000
  skip_existing_properties: true
  append_plexos_block_name: false
  exclude_pumping_from_reeds_storage_gen: true
multithreading_workers: 1
figure_file_format: svg
shift_leapday: false
auto_convert_units: true
read_csv_properties: true
user_defined_inputs_file: Marmot_user_defined_inputs_reeds_india.csv
plot_select_file: Marmot_plot_select_india.csv
plexos_properties_file: plexos_properties.csv
reeds_properties_file: reeds_properties.csv
reeds_india_properties_file: reeds_india_properties.csv
siip_properties_file: siip_properties.csv
