---
title: "PLEXOS Results"
author: "Created by: National Renewable Energy Laboratory (NREL)"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    css: custom.css
    toc: yes
    toc_float:
      collapsed: false
    number_sections: true
    df_print: paged
---

```{r setOptions, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# Options
fontsize = 20

# load packages, data and plotting functions
if(!require("pacman")){
  install.packages('devtools')
  require(remotes)
  install_version("pacman", version = "0.4.6", repos = "http://cran.us.r-project.org")
}

pacman::p_load(ggplot2, data.table, maptools, mapproj, RColorBrewer,tidyverse,magick,cowplot,
               rgeos, scales, stringr, rmarkdown, gdata, zoo, viridis,png,grid,dplyr)

#Read in file locations
inputs = data.table(read.csv('Marmot_user_defined_inputs.csv', header = T))
parent_dir = as.character(inputs[Input == 'Processed_Solutions_folder']$User_defined_value)
scenario_dir = as.character(inputs[Input == 'Main_scenario_plot']$User_defined_value)
agg_by_prefix = as.character(inputs[Input == 'AGG_BY']$User_defined_value)
plots_dir = paste0(parent_dir,'/',scenario_dir,'/Figures_Output/',agg_by_prefix,'_')

#Read in list of regions.
regions = data.table(read.csv('mapping_folder/Region_mapping.csv'))
regions = as.character(unique(pull(regions,agg_by_prefix)))

# set up default options for chunks, turn off error or warning messages
knitr::opts_chunk$set(echo=F, comment=NA, warning=F, message=F, include=T, 
                      dev='png', cache = F, fig.width = 5)

```

***
#Capacity Factor
##Capacity Factor (average output for all hours)
```{r capacity-factor, out.width = "50%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Capacity_Factor/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Capacity_Factor.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

##Average Output When Committed
```{r Average-Capacity-Out-When-Committed, out.width = "50%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Capacity_Factor/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Avg_Out_Committed.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

***
#Generation
##Stacked generation
```{r stacked-generation, out.width = "100%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Gen_stack/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Stacked_Gen_',scenario_dir,'.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
  }
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

##Unstacked generation
```{r unstacked-generation, out.width = "100%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Gen_stack/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Unstacked_Gen_',scenario_dir,'.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

#Ramping
##Capacity Started
```{r Capacity Started, out.width = "50%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Ramping/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Capacity_Started.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

***
#Total Generation
```{r total generation, out.width = "50%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Total_Gen_Stack/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Total_Generation .png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


***
#Installed Capacity
```{r Installed Capacity, out.width = "50%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Total_Installed_Capacity/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Total_Installed_Capacity.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```


***
#Transmission
##Net Export
```{r Net export, out.width = "50%", fig.asp = 0.675}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
plots_subdir = paste0(plots_dir,'Transmission/')
for (region in regions){
  img_fn = paste0(plots_subdir,region,'_Net_Export_',scenario_dir,'.png')
  if (img_fn %in% list.files(plots_subdir, full.names = T)){ print(ggdraw() + draw_image(img_fn) + draw_label(region, y = 0.975)) }
}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

